"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { StatusBadge } from "@/components/status-badge";
import type { InsightRow } from "@/types/domain";

export function InsightManager({ insights }: { insights: InsightRow[] }) { const router = useRouter(); const [message, setMessage] = useState(""); const [pending, setPending] = useState<string | null>(null);
  async function action(id: string, next: "completed" | "dismissed" | "snoozed") { if (next === "dismissed" && !confirm("Dismiss this insight? It remains in history but will leave the active list.")) return; setPending(id); setMessage(""); const response = await fetch(`/api/insights/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: next }) }); const body = await response.json(); setPending(null); if (!response.ok) return setMessage(body.error ?? "Could not update insight."); router.refresh(); }
  return <><div className="section-head"><h2>Active rule-generated insights</h2><span>{insights.length} shown</span></div>{message && <p className="error">{message}</p>}<section className="insight-list">{insights.length ? insights.map((insight) => <article className="insight-card" key={insight.id}><div><StatusBadge status={insight.priority} /><p className="insight-app">{insight.appName ?? "Portfolio"}</p></div><h2>{insight.title}</h2><p>{insight.observation}</p><p><strong>Next:</strong> {insight.recommendation}</p><footer>Confidence: {insight.confidence.replace("_", "-")} · Impact: {insight.impact} · Effort: {insight.effort}</footer><div className="insight-actions"><button disabled={pending === insight.id} onClick={() => action(insight.id, "completed")}>Mark done</button><button disabled={pending === insight.id} onClick={() => action(insight.id, "snoozed")}>Snooze 14d</button><button disabled={pending === insight.id} onClick={() => action(insight.id, "dismissed")}>Dismiss</button></div></article>) : <div className="notice"><h2>No active insights</h2><p>The existing rule engine has not produced an active insight for this filter.</p></div>}</section></>; }
