"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { KeywordRow } from "@/types/domain";

export function KeywordManager({ apps, rows }: { apps: Array<{ id: string; name: string }>; rows: KeywordRow[] }) { const router = useRouter(); const [mode, setMode] = useState<"add" | string | null>(null); const [message, setMessage] = useState(""); const [pending, setPending] = useState(false);
  async function request(url: string, method: string, body?: unknown): Promise<void> { setPending(true); setMessage(""); const response = await fetch(url, { method, headers: body ? { "Content-Type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json(); setPending(false); if (!response.ok) { setMessage(payload.error ?? "Request failed."); return; } setMode(null); router.refresh(); }
  return <><div className="section-head"><h2>Tracked keyword strategy</h2><button className="primary compact" onClick={() => setMode(mode === "add" ? null : "add")}>{mode === "add" ? "Close" : "Add keywords"}</button></div>{mode === "add" && <form action={(form) => request("/api/keywords", "POST", { appId: form.get("appId"), terms: String(form.get("terms")).split(/[\n,]/).map((item) => item.trim()).filter(Boolean), country: form.get("country"), priority: form.get("priority") })} className="management-form"><label>App<select name="appId">{apps.map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select></label><label>Keywords (comma or line separated)<textarea name="terms" required /></label><label>Storefront<input name="country" defaultValue="us" maxLength={2} required /></label><label>Priority<select name="priority" defaultValue="medium"><option>high</option><option>medium</option><option>low</option></select></label><button className="primary" disabled={pending}>{pending ? "Saving…" : "Start tracking"}</button></form>}{message && <p className="error">{message}</p>}<div className="table-wrap"><table><thead><tr><th>Keyword</th><th>App</th><th>Market</th><th>Rank</th><th>7d</th><th>30d</th><th>Best</th><th>Priority</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.length ? rows.map((row) => <KeywordLine key={row.linkId} row={row} editing={mode === row.linkId} pending={pending} onEdit={() => setMode(row.linkId)} onCancel={() => setMode(null)} onSave={(form) => request(`/api/keywords/${row.linkId}`, "PATCH", { term: form.get("term"), country: form.get("country"), priority: form.get("priority"), status: form.get("status") })} onDelete={() => { if (confirm(`Stop tracking “${row.term}” for ${row.appName}?`)) request(`/api/keywords/${row.linkId}`, "DELETE"); }} />) : <tr><td colSpan={10}>No keyword records match these filters.</td></tr>}</tbody></table></div></>; }

function KeywordLine({ row, editing, pending, onEdit, onCancel, onSave, onDelete }: { row: KeywordRow; editing: boolean; pending: boolean; onEdit: () => void; onCancel: () => void; onSave: (form: FormData) => void; onDelete: () => void }) { if (editing) return <tr><td colSpan={10}><form action={onSave} className="inline-form"><input name="term" defaultValue={row.term} required /><input name="country" defaultValue={row.country} maxLength={2} required /><select name="priority" defaultValue={row.priority}><option>high</option><option>medium</option><option>low</option></select><select name="status" defaultValue={row.status}><option>active</option><option>paused</option></select><button disabled={pending}>Save</button><button type="button" onClick={onCancel}>Cancel</button></form></td></tr>; const delta = (value: number | null) => value == null ? "—" : `${value > 0 ? "+" : ""}${value}`; return <tr><td>{row.term}</td><td>{row.appName}</td><td>{row.country.toUpperCase()}</td><td>{row.rank ? `#${row.rank}` : "Not ranked"}</td><td>{delta(row.change7d)}</td><td>{delta(row.change30d)}</td><td>{row.bestRank ? `#${row.bestRank}` : "—"}</td><td>{row.priority}</td><td>{row.status}</td><td><button onClick={onEdit}>Edit</button> <button onClick={onDelete}>Delete</button></td></tr>; }
