import { PageShell } from "@/components/page-shell";
import { listApps } from "@/repositories/apps-repository";
import { loadCompetitors } from "@/services/competitor-service";

export const dynamic = "force-dynamic";
export default async function CompetitorsPage({ searchParams }: { searchParams: Promise<{ app?: string }> }) {
  const { app: appId } = await searchParams; const [apps, competitors] = await Promise.all([listApps(), loadCompetitors(appId)]);
  return <PageShell title="Competitors"><form className="filter-form"><select name="app" defaultValue={appId ?? ""}><option value="">All tracked apps</option>{apps.map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select><button type="submit">Apply filters</button></form><div className="section-head"><h2>Tracked competitor metadata</h2><span>{competitors.length} records · latest snapshot only</span></div><div className="table-wrap"><table><thead><tr><th>Competitor</th><th>Tracked against</th><th>Rating</th><th>Version</th><th>Last captured</th></tr></thead><tbody>{competitors.length ? competitors.map((competitor) => <tr key={competitor.id}><td>{competitor.name}</td><td>{competitor.appName}</td><td>{competitor.rating ? `★ ${competitor.rating.toFixed(1)}` : "—"}</td><td>{competitor.version ?? "—"}</td><td>{competitor.capturedAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(competitor.capturedAt)) : "No snapshot yet"}</td></tr>) : <tr><td colSpan={5}>No competitors match this filter.</td></tr>}</tbody></table></div><section className="notice"><h2>Contested terms remain legacy-only</h2><p>The legacy console’s comparison logic combines competitor and owned rank snapshots. It will move after this catalogue and its metadata snapshots have been compared against production.</p></section></PageShell>;
}
