import { PageShell } from "@/components/page-shell";
import { listApps } from "@/repositories/apps-repository";
import { loadCompetitors } from "@/services/competitor-service";
import { loadContestedTerms } from "@/services/contested-terms-service";
import { requireUser } from "@/lib/auth";

export const dynamic = "force-dynamic";
export default async function CompetitorsPage({ searchParams }: { searchParams: Promise<{ app?: string }> }) {
  await requireUser(); const { app: appId } = await searchParams; const [apps, competitors, terms] = await Promise.all([listApps(), loadCompetitors(appId), loadContestedTerms(appId)]);
  return <PageShell title="Competitors"><form className="filter-form"><select name="app" defaultValue={appId ?? ""}><option value="">All tracked apps</option>{apps.map((app) => <option key={app.id} value={app.id}>{app.name}</option>)}</select><button type="submit">Apply filters</button></form><div className="section-head"><h2>Tracked competitor metadata</h2><span>{competitors.length} records · latest snapshot only</span></div><div className="table-wrap"><table><thead><tr><th>Competitor</th><th>Tracked against</th><th>Rating</th><th>Version</th><th>Last captured</th></tr></thead><tbody>{competitors.length ? competitors.map((competitor) => <tr key={competitor.id}><td>{competitor.name}</td><td>{competitor.appName}</td><td>{competitor.rating ? `★ ${competitor.rating.toFixed(1)}` : "—"}</td><td>{competitor.version ?? "—"}</td><td>{competitor.capturedAt ? new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(competitor.capturedAt)) : "No snapshot yet"}</td></tr>) : <tr><td colSpan={5}>No competitors match this filter.</td></tr>}</tbody></table></div><div className="section-head"><h2>Contested terms</h2><span>Largest competitor leads first · latest available snapshot</span></div><div className="table-wrap"><table><thead><tr><th>Term</th><th>Market</th><th>Competitor</th><th>Owned rank</th><th>Competitor rank</th><th>Priority</th></tr></thead><tbody>{terms.length ? terms.map((term) => <tr key={term.key}><td>{term.term}</td><td>{term.country.toUpperCase()}</td><td>{term.competitorName}</td><td>{term.ownedRank ? `#${term.ownedRank}` : "Not ranked"}</td><td>{term.competitorRank ? `#${term.competitorRank}` : "Not ranked"}</td><td>{term.priority}</td></tr>) : <tr><td colSpan={6}>No shared rank snapshots are available in the current comparison window.</td></tr>}</tbody></table></div></PageShell>;
}
