import { PageShell } from "@/components/page-shell";
import { StatusBadge } from "@/components/status-badge";
import { loadAppStoreConnectStatus } from "@/services/appstore-connect-service";
import { loadStorefrontMetricSummaries } from "@/services/storefront-metrics-service";

export const dynamic = "force-dynamic";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
export default async function AppStoreConnectPage() {
  const [connection, metrics] = await Promise.all([loadAppStoreConnectStatus(), loadStorefrontMetricSummaries()]);
  return <PageShell title="App Store Connect"><section className="metric-grid"><article className="metric-card"><p>Connection</p><strong><StatusBadge status={connection.status} /></strong><small>Existing server-side integration</small></article><article className="metric-card"><p>Last connection test</p><strong>{connection.lastTestOk === true ? "Passed" : connection.lastTestOk === false ? "Failed" : "Not run"}</strong><small>{date(connection.lastTestAt)}</small></article><article className="metric-card"><p>Last data sync</p><strong>{connection.lastSyncAt ? "Recorded" : "Waiting"}</strong><small>{date(connection.lastSyncAt)}</small></article><article className="metric-card"><p>Analytics reports</p><strong>{connection.reportRequests.length}</strong><small>Discovery &amp; Engagement requests</small></article></section><section className="notice"><h2>Server-side credentials retained</h2><p>{connection.lastTestMessage ?? "Connection details will appear after the existing integration is tested."} Sync and report-request controls remain in the legacy worker until the job handoff is verified.</p></section><div className="section-head"><h2>Discovery &amp; Engagement requests</h2><span>Existing App Store Connect records</span></div><div className="table-wrap"><table><thead><tr><th>App</th><th>Status</th><th>Last checked</th><th>Last error</th></tr></thead><tbody>{connection.reportRequests.length ? connection.reportRequests.map((request, index) => <tr key={`${request.appName}:${index}`}><td>{request.appName}</td><td><StatusBadge status={request.status} /></td><td>{date(request.lastCheckedAt)}</td><td>{request.lastError ?? "—"}</td></tr>) : <tr><td colSpan={4}>No report requests recorded.</td></tr>}</tbody></table></div><div className="section-head"><h2>Storefront activity</h2><span>Last 28 days · discovery reports</span></div><div className="table-wrap"><table><thead><tr><th>App</th><th>Country</th><th>Impressions</th><th>Product page views</th><th>Downloads</th><th>Conversion</th></tr></thead><tbody>{metrics.length ? metrics.map((metric) => <tr key={`${metric.appId}:${metric.country}`}><td>{metric.appName}</td><td>{metric.country.toUpperCase()}</td><td>{metric.impressions.toLocaleString()}</td><td>{metric.pageViews.toLocaleString()}</td><td>{metric.downloads.toLocaleString()}</td><td>{metric.pageViews ? `${((metric.downloads / metric.pageViews) * 100).toFixed(1)}%` : "—"}</td></tr>) : <tr><td colSpan={6}>No Discovery &amp; Engagement metric rows in this 28-day window.</td></tr>}</tbody></table></div></PageShell>;
}
