import { PageShell } from "@/components/page-shell";
import { StatusBadge } from "@/components/status-badge";
import { loadAppStoreConnectStatus } from "@/services/appstore-connect-service";

export const dynamic = "force-dynamic";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
export default async function AppStoreConnectPage() {
  const connection = await loadAppStoreConnectStatus();
  return <PageShell title="App Store Connect"><section className="metric-grid"><article className="metric-card"><p>Connection</p><strong><StatusBadge status={connection.status} /></strong><small>Existing server-side integration</small></article><article className="metric-card"><p>Last connection test</p><strong>{connection.lastTestOk === true ? "Passed" : connection.lastTestOk === false ? "Failed" : "Not run"}</strong><small>{date(connection.lastTestAt)}</small></article><article className="metric-card"><p>Last data sync</p><strong>{connection.lastSyncAt ? "Recorded" : "Waiting"}</strong><small>{date(connection.lastSyncAt)}</small></article><article className="metric-card"><p>Analytics reports</p><strong>{connection.reportRequests.length}</strong><small>Discovery &amp; Engagement requests</small></article></section><section className="notice"><h2>Server-side credentials retained</h2><p>{connection.lastTestMessage ?? "Connection details will appear after the existing integration is tested."} Sync and report-request controls remain in the legacy worker until the job handoff is verified.</p></section><div className="section-head"><h2>Discovery &amp; Engagement requests</h2><span>Existing App Store Connect records</span></div><div className="table-wrap"><table><thead><tr><th>App</th><th>Status</th><th>Last checked</th><th>Last error</th></tr></thead><tbody>{connection.reportRequests.length ? connection.reportRequests.map((request, index) => <tr key={`${request.appName}:${index}`}><td>{request.appName}</td><td><StatusBadge status={request.status} /></td><td>{date(request.lastCheckedAt)}</td><td>{request.lastError ?? "—"}</td></tr>) : <tr><td colSpan={4}>No report requests recorded.</td></tr>}</tbody></table></div></PageShell>;
}
