export function rates(input:{impressions:number;taps:number;installs:number;spend:number}){return {tapThroughRate:input.impressions?input.taps/input.impressions:null,conversionRate:input.taps?input.installs/input.taps:null,averageCpt:input.taps?input.spend/input.taps:null,averageCpa:input.installs?input.spend/input.installs:null};}

type RawRow={date?:unknown;total?:Record<string,unknown>;metadata?:Record<string,unknown>;granularity?:RawRow[]};
export type DailyCampaignMetric={date:string;country:string;impressions:number;taps:number;installs:number;newDownloads:number;redownloads:number;spend:number;currency:string|null;rawPayload:RawRow};
const asNumber=(value:unknown)=>typeof value==="number"?value:typeof value==="string"?Number(value)||0:0;
export function dailyCampaignMetrics(raw:Record<string,unknown>):DailyCampaignMetric[]{const root=(raw.data??raw) as {reportingDataResponse?:{row?:RawRow[]};row?:RawRow[]};const rows=root.reportingDataResponse?.row??root.row??[];return rows.flatMap(row=>(row.granularity??[]).flatMap(day=>{const date=typeof day.date==="string"?day.date:"";if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return [];const total=day.total??{};const spend=total.localSpend as {amount?:unknown;currency?:unknown}|undefined;const country=typeof day.metadata?.countryOrRegion==="string"?day.metadata.countryOrRegion:typeof row.metadata?.countryOrRegion==="string"?row.metadata.countryOrRegion:"all";return [{date,country:country.toLowerCase(),impressions:asNumber(total.impressions),taps:asNumber(total.taps),installs:asNumber(total.installs),newDownloads:asNumber(total.newDownloads),redownloads:asNumber(total.redownloads),spend:asNumber(spend?.amount),currency:typeof spend?.currency==="string"?spend.currency:null,rawPayload:day}];}));}
export type SearchTermMetric={date:string;country:string;campaignId:string|null;adGroupId:string|null;keywordId:string|null;searchTerm:string;sourceKeywordText:string|null;matchSource:string|null;impressions:number;taps:number;installs:number;spend:number;currency:string|null;rawPayload:RawRow};
const stringField=(value:unknown)=>typeof value==="string"&&value.trim()?value:null;
function reportingRows(raw:Record<string,unknown>){const data=raw.data as {reportingDataResponse?:{row?:RawRow[]}}|undefined;const root=raw as {reportingDataResponse?:{row?:RawRow[]};row?:RawRow[]};return data?.reportingDataResponse?.row??root.reportingDataResponse?.row??root.row??[];}
export function searchTermMetrics(raw:Record<string,unknown>,fallbackDate:string):SearchTermMetric[]{return reportingRows(raw).flatMap(row=>{const parts=row.granularity?.length?row.granularity:[row];return parts.flatMap(part=>{const metadata={...(row.metadata??{}),...(part.metadata??{})};const total=part.total??row.total??{};const date=stringField(part.date)??stringField(row.date)??fallbackDate;if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return [];const searchTerm=stringField(metadata.searchTermText)??stringField((part as Record<string,unknown>).searchTermText)??stringField((row as Record<string,unknown>).searchTermText);if(!searchTerm)return [];const spend=total.localSpend as {amount?:unknown;currency?:unknown}|undefined;const country=stringField(metadata.countryOrRegion)??"all";return [{date,country:country.toLowerCase(),campaignId:stringField(metadata.campaignId),adGroupId:stringField(metadata.adGroupId),keywordId:stringField(metadata.keywordId),searchTerm,sourceKeywordText:stringField(metadata.keyword),matchSource:stringField(metadata.searchTermSource)??stringField(metadata.matchType),impressions:asNumber(total.impressions),taps:asNumber(total.taps),installs:asNumber(total.installs) || asNumber(total.totalInstalls),spend:asNumber(spend?.amount),currency:stringField(spend?.currency),rawPayload:part}];});});}
export type StoredDailyMetric={metricDate:string;impressions:number;taps:number;installs:number;spend:number};
export function summarizeDailyMetrics(rows:StoredDailyMetric[]){const totals=rows.reduce((sum,row)=>({impressions:sum.impressions+row.impressions,taps:sum.taps+row.taps,installs:sum.installs+row.installs,spend:sum.spend+row.spend}),{impressions:0,taps:0,installs:0,spend:0});return {...totals,...rates(totals)};}
