import { PageShell } from "@/components/page-shell";
import { rates } from "@/lib/apple-ads/reporting";
import { requireUser } from "@/lib/auth";
import { getAppleAdsReporting } from "@/repositories/apple-ads-reporting-repository";
import Link from "next/link";

export const dynamic="force-dynamic";
const formatNumber=(value:number)=>new Intl.NumberFormat("en-US",{maximumFractionDigits:0}).format(value);
const formatMoney=(value:number,currency:string|null)=>new Intl.NumberFormat("en-US",{style:"currency",currency:currency??"USD",maximumFractionDigits:2}).format(value);
const formatPercent=(value:number|null)=>value===null?"—":`${(value*100).toFixed(1)}%`;
export default async function AppleAdsReportingPage(){const user=await requireUser();const {rows,summary}=await getAppleAdsReporting(user.id);const currency=rows.find(row=>row.currency)?.currency??null;const latest=rows[0]?.metricDate;return <PageShell title="Apple Ads reporting"><section className="notice"><h2>Merged into Campaigns</h2><p>Campaign performance now appears alongside imported campaign structure in <Link href="/apple-ads-lab/structure">Apple Ads → Campaigns</Link>. This daily report table remains temporarily during migration.</p></section>{rows.length?<><section className="metric-grid"><article className="metric-card"><p>Impressions</p><strong>{formatNumber(summary.impressions)}</strong><small>Imported daily data</small></article><article className="metric-card"><p>Taps</p><strong>{formatNumber(summary.taps)}</strong><small>{formatPercent(summary.tapThroughRate)} tap-through rate</small></article><article className="metric-card"><p>Installs</p><strong>{formatNumber(summary.installs)}</strong><small>{formatPercent(summary.conversionRate)} tap-to-install</small></article><article className="metric-card"><p>Spend</p><strong>{formatMoney(summary.spend,currency)}</strong><small>{summary.averageCpa===null?"No CPA yet":`${formatMoney(summary.averageCpa,currency)} per install`}</small></article></section><div className="section-head"><h2>Daily performance</h2><span>Latest imported date: {latest}</span></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Campaign</th><th>Impressions</th><th>Taps</th><th>Installs</th><th>Spend</th><th>CPA</th></tr></thead><tbody>{rows.map(row=>{const rowRates=rates(row);return <tr key={row.id}><td>{row.metricDate}</td><td>{row.campaignName}</td><td>{formatNumber(row.impressions)}</td><td>{formatNumber(row.taps)}</td><td>{formatNumber(row.installs)}</td><td>{formatMoney(row.spend,row.currency)}</td><td>{rowRates.averageCpa===null?"—":formatMoney(rowRates.averageCpa,row.currency)}</td></tr>;})}</tbody></table></div></>:<section className="notice"><h2>Ready for the first report</h2><p>There are no daily performance rows yet. Use <strong>Sync last 7 days</strong> on Apple Ads Lab once the campaign has delivered. A paused campaign with no delivery correctly leaves this report empty.</p></section>}</PageShell>;}
